### PR TITLE
Update xlink:href refs on id cleanup

### PR DESCRIPTION
**Pull request by amogower**
Noticed that xlink:href refs weren't being updated with the new ids so have added a regex match and replacement for those.

### CODE REVIEW

**Comment by iest** [comment]
Thanks for the PR @amogower! Could you please add a test to `__tests__` to verify what you've changed does the job? 🙌

**Comment by amogower** [comment]
@iest np, test should be in the PR now 👍

**Comment by amogower** [comment]
Actually found a bug with the getIds regexp being greedy so have fixed that, updated tests and also added a mask url reference regexp + replacement.

**Comment by iest** [comment]
@amogower Apologies for the (oops, over a year!) slow response on this one — are you using these changes in production somewhere, and are they working as expected?

I'm gonna revamp the repo soon so I'd love to pull these changes in.

**Comment by iest** [comment]
This work was used as part of https://github.com/iest/babel-plugin-inline-svg/pull/22 🙌

**Pull request closed without merging**
